# Generated by Django 6.1 on 2026-08-18 16:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, default='', help_text='GST Identification Number (15 characters)', max_length=15)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('state_code', models.CharField(blank=True, default='', max_length=10)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=100)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=30)),
                ('bank_ifsc', models.CharField(blank=True, default='', help_text='IFSC code (11 characters)', max_length=11)),
                ('terms_and_conditions', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Profile',
                'verbose_name_plural': 'Business Profiles',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('gstin', models.CharField(blank=True, db_index=True, default='', help_text='GST Identification Number — optional for unregistered buyers', max_length=15)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('state_code', models.CharField(blank=True, default='', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='customer_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Invoice/bill number — supports formats: 93, INV-93, 2026/93', max_length=50)),
                ('invoice_date', models.DateField(help_text='The business/invoice date printed on the document')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=10)),
                ('transaction_type', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], default='CASH', max_length=6)),
                ('transport_name', models.CharField(blank=True, default='', max_length=255)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=20)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='CGST rate as a percentage, e.g. 9.00', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SGST rate as a percentage, e.g. 9.00', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('igst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IGST rate as a percentage, e.g. 18.00', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tcs_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TCS rate as a percentage, e.g. 1.00', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tcs_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reverse_charge', models.BooleanField(default=False, help_text='Whether reverse charge mechanism applies to this invoice')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_in_words', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='The business that issued this invoice', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.businessprofile')),
                ('customer', models.ForeignKey(help_text='The buyer receiving this invoice', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.customer')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(help_text='Row sequence number within the invoice (1, 2, 3, …)')),
                ('product_name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(blank=True, default='', help_text='HSN / SAC code stored as a string to preserve leading zeros', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity (3 decimal places to support MT, KG, etc.)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('unit', models.CharField(blank=True, default='', help_text='Unit of measure, e.g. MT, KG, TON', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount', models.DecimalField(decimal_places=2, help_text='Line total = quantity × rate (calculated by service layer)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['invoice', 'serial_number'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoice_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['business', 'invoice_date'], name='invoice_business_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('business', 'invoice_number'), name='unique_invoice_number_per_business'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('taxable_amount__gte', 0)), name='invoice_taxable_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='invoice_total_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('cgst_rate__gte', 0)), name='invoice_cgst_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('sgst_rate__gte', 0)), name='invoice_sgst_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('igst_rate__gte', 0)), name='invoice_igst_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('tcs_rate__gte', 0)), name='invoice_tcs_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'serial_number'), name='unique_serial_number_per_invoice'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='item_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='item_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='item_amount_non_negative'),
        ),
    ]
