# Generated by Django 6.1 on 2026-08-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive customers are hidden from new-invoice selection but remain in historical records.'),
        ),
    ]
