# Generated by Django 6.1 on 2026-08-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_is_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoice_number_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['vehicle_number'], name='vehicle_number_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['transaction_type'], name='transaction_type_idx'),
        ),
    ]
