# Generated by Django 6.1 on 2026-08-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoice_invoice_number_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='google_drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='google_drive_file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='google_drive_status',
            field=models.CharField(choices=[('NOT_UPLOADED', 'Not Uploaded'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('FAILED', 'Failed')], default='NOT_UPLOADED', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='google_drive_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
