# Generated by Django 6.1 on 2026-08-19 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invoice_google_drive_file_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who registered and owns this business profile.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
