# Generated by Django 6.1 on 2026-08-19 08:47

from django.db import migrations, models


def populate_gst_registered(apps, schema_editor):
    Customer = apps.get_model('core', 'Customer')
    Customer.objects.exclude(gstin="").update(gst_registered=True)

def reverse_populate_gst_registered(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_businessprofile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gst_registered',
            field=models.BooleanField(default=False, help_text='Whether this customer has a valid GST registration'),
        ),
        migrations.RunPython(populate_gst_registered, reverse_populate_gst_registered),
    ]
