# Generated by Django 6.1 on 2026-08-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_customer_gst_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='google_oauth_refresh_token',
            field=models.CharField(blank=True, default='', help_text="OAuth 2.0 refresh token for uploading to the owner's Google Drive", max_length=255),
        ),
    ]
