# Generated by Django 6.1 on 2026-08-19 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_businessprofile_google_oauth_refresh_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='google_drive_folder_id',
            field=models.CharField(blank=True, default='', help_text='Google Drive Folder ID where invoices are uploaded', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='business',
            field=models.ForeignKey(help_text='The business that owns this customer record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.businessprofile'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='owner',
            field=models.OneToOneField(blank=True, help_text='The user who registered and owns this business profile.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
