# Generated by Django 6.1 on 2026-08-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20260819_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aadhaar_no',
            field=models.CharField(blank=True, default='', help_text='Aadhaar Number — alternative identification for unregistered buyers', max_length=12),
        ),
    ]
