# Generated by Django 4.2.30 on 2026-08-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customer_aadhaar_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gst_legal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_trade_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_verified',
            field=models.BooleanField(default=False, help_text='Whether this GSTIN has been successfully verified with the GST API'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the GST verification was performed', null=True),
        ),
    ]
