# Generated by Django 6.1 on 2026-08-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customer_gst_legal_name_customer_gst_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='pincode',
            field=models.CharField(blank=True, help_text='6-digit Indian Pincode', max_length=6, null=True),
        ),
    ]
