# Generated by Django 6.1 on 2026-08-21 17:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_businessprofile_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(blank=True, help_text='Name of the party if not a registered customer (e.g., external supplier or transporter).', max_length=255)),
                ('transaction_type', models.CharField(choices=[('RECEIVABLE', 'Receivable'), ('PAYABLE', 'Payable')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Original transaction amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference', models.CharField(blank=True, help_text='Invoice number, PO number, or reason', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='The business profile this ledger entry belongs to (for data isolation).', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.businessprofile')),
                ('customer', models.ForeignKey(blank=True, help_text='Linked customer (if the party is a registered customer).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.customer')),
            ],
            options={
                'verbose_name_plural': 'Ledger Entries',
            },
        ),
        migrations.CreateModel(
            name='LedgerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_entry', models.ForeignKey(help_text='The ledger entry this payment applies to. RESTRICT prevents deleting a ledger if payments exist.', on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='core.ledgerentry')),
            ],
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['business', 'status'], name='core_ledger_busines_0e93d6_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['business', 'transaction_type'], name='core_ledger_busines_2f3609_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['business', 'created_at'], name='core_ledger_busines_0d3db9_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='ledgerpayment',
            index=models.Index(fields=['ledger_entry', 'payment_date'], name='core_ledger_ledger__205063_idx'),
        ),
    ]
