# Generated by Django 6.1 on 2026-08-21 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ledgerentry_ledgerpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='invoice',
            field=models.OneToOneField(blank=True, help_text='The invoice that generated this ledger entry (if applicable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='core.invoice'),
        ),
    ]
