# Generated by Django 4.2.30 on 2026-08-22 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_ledgerentry_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerpayment',
            name='status',
            field=models.CharField(choices=[('RECORDED', 'Recorded'), ('VOIDED', 'Voided')], default='RECORDED', max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('VOIDED', 'Voided')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="e.g. 'Payment recorded', 'Ledger entry voided'", max_length=255)),
                ('record_type', models.CharField(help_text="e.g. 'LedgerEntry', 'LedgerPayment'", max_length=50)),
                ('record_id', models.PositiveIntegerField(help_text='The ID of the affected record')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, help_text='Store previous and new state diffs if applicable', null=True)),
                ('business', models.ForeignKey(help_text='The business this action belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.businessprofile')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['business', 'record_type', 'record_id'], name='core_auditl_busines_5ff8ef_idx')],
            },
        ),
    ]
