# Generated by Django 4.2.30 on 2026-08-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ledgerpayment_status_alter_ledgerentry_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='party_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('TRANSPORTER', 'Transporter'), ('OTHER', 'Other')], db_index=True, default='CUSTOMER', help_text='The role of this party (Customer, Supplier, Transporter, Other)', max_length=20),
        ),
    ]
