# Generated by Django 4.2.30 on 2026-08-23 15:01

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customer_party_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerpayment',
            name='proof_document',
            field=models.FileField(blank=True, help_text='Optional supporting documentation for the payment.', null=True, upload_to='payment_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf']), core.models.validate_file_size]),
        ),
    ]
