# Generated by Django 4.2.30 on 2026-08-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ledgerpayment_proof_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='entry_date',
            field=models.DateField(blank=True, help_text='Date associated with this entry, separate from creation time', null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='order_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='serial_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='tons',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='truck_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
