# Generated by Django 4.2.30 on 2026-08-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ledgerentry_entry_date_ledgerentry_order_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('gstin', models.CharField(blank=True, db_index=True, default='', help_text='GST Identification Number — optional', max_length=15)),
                ('aadhaar_no', models.CharField(blank=True, default='', help_text='Aadhaar Number — optional', max_length=12)),
                ('address', models.TextField(blank=True, default='')),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive suppliers are archived/hidden from selection.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='The business that owns this supplier record.', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.businessprofile')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='supplier_name_idx')],
            },
        ),
    ]
