# Generated by Django 4.2.30 on 2026-08-26 13:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(db_index=True)),
                ('purchase_order_no', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('serial_no', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('truck_no', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('quantity_tons', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('rate_per_ton', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive purchases are archived/soft-deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='The business that owns this purchase record.', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.businessprofile')),
                ('supplier', models.ForeignKey(help_text='The supplier of the coal.', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.supplier')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_tons__gt', 0)), name='purchase_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('rate_per_ton__gte', 0)), name='purchase_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('gst_rate__gte', 0)), name='purchase_gst_rate_non_negative'),
        ),
    ]
