# Generated by Django 4.2.30 on 2026-08-26 14:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_purchase_purchase_purchase_quantity_positive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(db_index=True)),
                ('sale_order_no', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('serial_no', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('truck_no', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('quantity_tons', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('rate_per_ton', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive sales are archived/soft-deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='The business that owns this sale record.', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.businessprofile')),
                ('customer', models.ForeignKey(help_text='The customer who purchased the coal.', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.customer')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_tons__gt', 0)), name='sale_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('rate_per_ton__gte', 0)), name='sale_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('gst_rate__gte', 0)), name='sale_gst_rate_non_negative'),
        ),
    ]
