# Generated by Django 4.2.30 on 2026-08-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_expense_expense_expense_amount_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='purchase_order_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='sale_order_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
