# Generated by Django 4.2.30 on 2026-08-27 11:59

from django.db import migrations


def copy_order_nos(apps, schema_editor):
    LedgerEntry = apps.get_model('core', 'LedgerEntry')
    for entry in LedgerEntry.objects.all():
        if entry.order_no:
            if entry.transaction_type == 'RECEIVABLE':
                entry.sale_order_no = entry.order_no
            elif entry.transaction_type == 'PAYABLE':
                entry.purchase_order_no = entry.order_no
            entry.save(update_fields=['sale_order_no', 'purchase_order_no'])

def reverse_copy(apps, schema_editor):
    LedgerEntry = apps.get_model('core', 'LedgerEntry')
    for entry in LedgerEntry.objects.all():
        if entry.sale_order_no:
            entry.order_no = entry.sale_order_no
        elif entry.purchase_order_no:
            entry.order_no = entry.purchase_order_no
        entry.save(update_fields=['order_no'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_ledgerentry_purchase_order_no_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_order_nos, reverse_copy),
    ]
