# Generated by Django 4.2.30 on 2026-08-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20260827_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='order_no',
        ),
    ]
