# Generated by Django 4.2.30 on 2026-08-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_ledgerentry_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='sale',
            field=models.OneToOneField(blank=True, help_text='The sale this receivable is linked to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable', to='core.sale'),
        ),
    ]
