# Generated by Django 4.2.30 on 2026-08-27 12:29

from django.db import migrations


def link_sales_to_ledger(apps, schema_editor):
    LedgerEntry = apps.get_model('core', 'LedgerEntry')
    Sale = apps.get_model('core', 'Sale')

    # Look at all 'RECEIVABLE' entries that don't have a sale linked
    entries = LedgerEntry.objects.filter(transaction_type='RECEIVABLE', sale__isnull=True)
    
    for entry in entries:
        if not entry.customer:
            continue
            
        # Try to find matching Sale based on provided identifying fields
        query = Sale.objects.filter(customer=entry.customer)
        if entry.sale_order_no:
            query = query.filter(sale_order_no=entry.sale_order_no)
        if entry.serial_no:
            query = query.filter(serial_no=entry.serial_no)
        if entry.truck_no:
            query = query.filter(truck_no=entry.truck_no)
            
        # Only link if there is exactly ONE confident match to avoid ambiguity
        if query.count() == 1:
            entry.sale = query.first()
            entry.save(update_fields=['sale'])

def reverse_link(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_ledgerentry_sale'),
    ]

    operations = [
        migrations.RunPython(link_sales_to_ledger, reverse_link),
    ]
